#!/bin/sh

set -eux

docker build -t toxchat/c-toxcore:sources -f other/docker/sources/Dockerfile .
docker build -t toxchat/c-toxcore:prof -f other/docker/prof/Dockerfile .
docker run --name toxcore-prof --rm -it -p "28192:80" toxchat/c-toxcore:prof
