---
cirrus-ci_task:
  container:
    image: l.gcr.io/google/bazel:2.2.0
    cpu: 8
    memory: 12G
  configure_script:
    - cd .. && mv cirrus-ci-build c-toxcore
    - git clone --depth=1 https://github.com/TokTok/toktok-stack cirrus-ci-build
    - mv c-toxcore cirrus-ci-build
    - cd cirrus-ci-build
    - tools/setup-ci
    - bazel version
  test_all_script:
    - RUN_TEST="bazel test --copt=-DUSE_IPV6=0 -c opt -k //c-toxcore/..."
    - $RUN_TEST || $RUN_TEST
