---
cirrus-ci_task:
  container:
    image: toxchat/toktok-stack:0.0.10
    cpu: 2
    memory: 2G
  configure_script:
    - /src/workspace/tools/inject-repo c-toxcore
  test_all_script:
    - TEST="bazel test -k
      --config=ci
      --config=release
      //c-toxcore/..."
    - $TEST || $TEST || $TEST || $TEST
