---
cirrus-ci_task:
  container:
    image: toxchat/toktok-stack:0.0.18
    cpu: 2
    memory: 2G
  configure_script:
    - /src/workspace/tools/inject-repo c-toxcore
    # Work around "FATAL: corrupt installation: file '/home/builder/.cache/bazel/_bazel_builder/install/f439a981a1e06f45be981c123f9858d5/A-server.jar' is missing or modified"
    # Clearing the cache through the Cirrus web UI doesn't fix, but this does.
    - rm -rf /home/builder/.cache/bazel/
  test_all_script:
    - bazel test -k
        --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
        --build_tag_filters=-haskell
        --test_tag_filters=-haskell
        --remote_download_minimal
        --config=release
        --
        //c-toxcore/...
        -//c-toxcore/auto_tests:tcp_relay_test # TODO(robinlinden): Why does this pass locally but not in Cirrus?

cimple_task:
  container:
    image: toxchat/toktok-stack:0.0.18
    cpu: 2
    memory: 4G
  configure_script:
    - /src/workspace/tools/inject-repo c-toxcore
  test_all_script:
    - bazel test -k
        --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
        --build_tag_filters=haskell
        --test_tag_filters=haskell
        --
        //c-toxcore/...
