---
cirrus-ci_task:
  container:
    image: toxchat/toktok-stack:0.0.23-third_party
    cpu: 2
    memory: 2G
  configure_script:
    - /src/workspace/tools/inject-repo c-toxcore
  test_all_script:
    - cd /src/workspace && bazel test -k
        --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
        --build_tag_filters=-haskell
        --test_tag_filters=-haskell
        --remote_download_minimal
        --config=release
        --
        //c-toxcore/...
        -//c-toxcore/auto_tests:tcp_relay_test # TODO(robinlinden): Why does this pass locally but not in Cirrus?

cimple_task:
  container:
    image: toxchat/toktok-stack:0.0.23-third_party
    cpu: 2
    memory: 4G
  configure_script:
    - /src/workspace/tools/inject-repo c-toxcore
  test_all_script:
    - cd /src/workspace && bazel test -k
        --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
        --build_tag_filters=haskell
        --test_tag_filters=haskell
        --config=release
        --
        //c-toxcore/...
