sudo: true
dist: trusty
language: c
compiler:
  - gcc
#  - clang

env:
  matrix:
    - BUILD=toxcore
#    - BUILD=hstox

cache:
  directories:
    - $HOME/cache

before_script:
  - sudo add-apt-repository -y ppa:avsm/ppa
  - sudo add-apt-repository -y ppa:chris-lea/libsodium
  - sudo apt-get update
  - sudo apt-get install -y libsodium-dev libvpx-dev libopus-dev check opam
  - other/travis/${BUILD}_before_script.sh

script:
  - other/travis/${BUILD}_script.sh

after_script:
  - other/travis/${BUILD}_after_script.sh

#notifications:
#  email: false
#
#  irc:
#    channels:
#      - "chat.freenode.net#tox-dev"
#    on_success: always
#    on_failure: always
