---
image: Visual Studio 2019

cache:
  - '%USERPROFILE%\.conan -> conanfile.py'

install:
  - set PATH=C:\Python310-x64\Scripts;%PATH%
  - py -3 -m pip install conan

before_build:
  - git submodule update --init --recursive
  - conan install -if _build .

build_script:
  - conan build -bf _build -if _build .

test_script:
  - set CONAN_CPU_COUNT=50
  - set CTEST_OUTPUT_ON_FAILURE=1
  - conan install -if _build -o with_tests=True .
  - conan build -bf _build -if _build .
