#!/bin/bash

set -eu

CACHEDIR="$HOME/cache"

. ".github/scripts/flags-$CC.sh"
add_flag -Werror
add_flag -fdiagnostics-color=always
add_flag -flto=thin  # for cfi
add_flag -fno-omit-frame-pointer
add_flag -fsanitize=cfi
cmake -B_build -H. -GNinja \
  -DCMAKE_C_FLAGS="$C_FLAGS" \
  -DCMAKE_CXX_FLAGS="$CXX_FLAGS" \
  -DCMAKE_EXE_LINKER_FLAGS="$LD_FLAGS" \
  -DCMAKE_SHARED_LINKER_FLAGS="$LD_FLAGS" \
  -DCMAKE_INSTALL_PREFIX:PATH="$PWD/_install" \
  -DCMAKE_UNITY_BUILD=ON \
  -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
  -DMIN_LOGGER_LEVEL=TRACE \
  -DMUST_BUILD_TOXAV=ON \
  -DNON_HERMETIC_TESTS=ON \
  -DSTRICT_ABI=ON \
  -DENABLE_SHARED=OFF \
  -DTEST_TIMEOUT_SECONDS=120 \
  -DUSE_IPV6=OFF \
  -DAUTOTEST=ON

cd _build

ninja install -j"$(nproc)"

ctest -j50 --output-on-failure --rerun-failed --repeat until-pass:6
