#!/bin/bash

set -ex

SOURCE_DIR="$1"
ASTYLE="$2"

# Go to the source root.
if [ -z "$SOURCE_DIR" ]; then
  SOURCE_DIR=.
fi
cd "$SOURCE_DIR"

if [ -z "$ASTYLE" ] || ! which "$ASTYLE"; then
  ASTYLE=astyle
fi

if ! which "$ASTYLE"; then
  # If we couldn't find or install an astyle binary, don't do anything.
  echo "Could not find an astyle binary; please install astyle."
  exit 1
fi

FIND="find ."
FIND="$FIND '(' -name '*.[ch]' ')'"
FIND="$FIND -and -not -name '*.api.h'"
FIND="$FIND -and -not -wholename './super_donators/*'"
FIND="$FIND -and -not -wholename './third_party/*'"
FIND="$FIND -and -not -wholename './toxencryptsave/crypto_pwhash*'"

readarray -t C_SOURCES <<<"$(eval "$FIND")"
readarray -t CC_SOURCES <<<"$(find . '(' -name '*.cc' -or -name '*.hh' ')')"

# Format C++ sources with clang-format.
for bin in clang-format-11 clang-format-7 clang-format-6.0 clang-format-5.0 clang-format; do
  if which "$bin"; then
    "$bin" -i "${CC_SOURCES[@]}"
    break
  fi
done

# Format C sources with astyle. We can't use clang-format, because it strongly
# messes up formatting of non_null annotations.
"$ASTYLE" -n --options=other/astyle/astylerc "${C_SOURCES[@]}"

#git diff --color=always --exit-code
