#!/usr/bin/env python3

import glob as py_glob
import os
import subprocess
import sys

LIBS = {}


def load(bzl, *syms):
    pass


def exports_files(srcs, visibility=None):
    pass


def cc_library(name, **kwargs):
    LIBS[name] = kwargs


def cc_test(name, **kwargs):
    pass


def cc_fuzz_test(name, **kwargs):
    pass


def select(selector):
    return selector["//tools/config:linux"]


def glob(include):
    return [
        f[len("toxcore/") :]
        for p in include
        for f in py_glob.glob(os.path.join("toxcore", p))
    ]


def alias(name, actual, visibility):
    pass


def sh_library(name, **kwargs):
    pass


def main():
    with open("toxcore/BUILD.bazel", "r") as fh:
        exec(fh.read())

    with open("module.modulemap", "w") as fh:
        for name, lib in LIBS.items():
            fh.write("module " + name + " {\n")
            for hdr in lib["hdrs"]:
                fh.write(f'  header "toxcore/{hdr}"\n')
            for dep in lib.get("deps", []):
                if dep[0] == ":":
                    fh.write(f"  use {dep[1:]}\n")
            fh.write("}\n")

    srcs = sorted(
        set(
            os.path.join("toxcore", src)
            for lib in LIBS.values()
            for src in lib.get("srcs", [])
        )
    )
    for src in srcs:
        print(f"Validating {src}", file=sys.stderr)
        subprocess.run(
            [
                "clang",
                "-xc++",
                "-fsyntax-only",
                "-Wall",
                "-Werror",
                "-Wno-missing-braces",
                "-std=c++23",
                "-fdiagnostics-color=always",
                "-fmodules",
                "-fmodules-decluse",
                "-fmodule-map-file=module.modulemap",
                src,
            ],
            check=True,
        )


if __name__ == "__main__":
    main()
