name: docker

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-bootstrapd-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Docker Build
        run: .github/scripts/tox-bootstrapd-docker local
      - name: Push latest image to DockerHub
        if: ${{ github.event_name == 'push' }}
        run: docker push toxchat/bootstrap-node:latest
      - name: Push versioned image to DockerHub
        if: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/') }}
        run: docker push toxchat/bootstrap-node:"$(other/print-version)"
